### ISSUE TITLE
Support composition for Korean/Japanese etc.

### ISSUE THREAD

**Issue by michael** [michael/svedit#87]
As reported by @johannesmutter:

- [ ] On iOS Safari (and maybe macOS too?) character compositions are not working for e.g. Korean. Is this something language specific to be implemented by the application?

Try typing these characters:
ㄱㅏㄴㅏㄷㅏ

They should become:
나나나

https://github.com/user-attachments/assets/e40cfc47-6d44-429e-9d6d-a4510fd61ba8

**Comment by michael** [comment]
Fixed via https://github.com/michael/svedit/pull/103

**Comment by johannesmutter** [comment]
tested just now again, but still not working for e.g. Korean and Japanese in iOS Safari. Yes, characters are now composed, but not in the right order.

`ㄱ + ㅏ` → `가`

but we get instead:

`ㄱ가`

and if we delete and type again `ㄱ + ㅏ` we get `난나나`

So looks like a previous composition is also not cleaned up.
